config/routes.rb
Rails.application.routes.draw do
  resources :questions do 
    resources :answers
    
    collection do
      post :purge
    end
  end

  get '/', to: redirect('/questions')
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, length: { maximum: 2000, minimum: 30 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  validates :title, :body, presence: true
  validates :title, length: { maximum: 200, minimum: 10 }
  validates :body, length: { maximum: 1000 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question
  before_action :set_answer, only: %i[show edit update destroy]

  # GET /answers/new
  def new
    @answer = @question.answers.build
  end

  # POST /answers or /answers.json
  def create
    @answer = @question.answers.build(answer_params)

    respond_to do |format|
      if @answer.save
        format.html do
          redirect_to question_url(@question), notice: "Answer was successfully created."
        end
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @answer.destroy

    respond_to do |format|
      format.html do
        redirect_to question_url(@question), notice: "Answer was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = @question.answers.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]

  # GET /questions or /questions.json
  def index
    @questions = Question.includes(:answers).limit(10)
  end

  # GET /questions/1 or /questions/1.json
  def show; end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit; end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save

        ActionCable.server.broadcast "questions", {}

        format.html do
          redirect_to question_url(@question), notice: "Question was successfully created."
        end
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html do
          redirect_to question_url(@question), notice: "Question was successfully updated."
        end
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def purge
    Question.delete_all

    redirect_to questions_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.includes(:answers).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def question_params
    params.require(:question).permit(:title, :body)
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/answers/_answer.html.erb
<div id="<%= dom_id answer %>">
  <div class="my-5">
    <p >
      <%= answer.body %>
    </p>

    <h6 class="text-gray-400 text-sm">
      Answered on <%= answer.created_at.to_s(:human) %>
    <h6>
  </div>

  <% if action_name != "show" %>
    <%= link_to "Show this answer", answer, class: "rounded-lg py-2 px-4 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this answer', edit_answer_path(answer), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/answers/_form.html.erb
<%= form_with(model: [@question, answer], class: "contents") do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-2 px-4 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/answers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Answers</h1>
    <%= link_to 'New answer', new_answer_path, class: "rounded-lg py-2 px-4 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="answers" class="min-w-full">
    <%= render @answers %>
  </div>
</div>

app/views/answers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New answer</h1>

  <%= render "form", answer: @answer %>

  <%= link_to 'Back to question', question_path(@question), class: "ml-2 rounded-lg py-2 px-4 bg-gray-100 inline-block font-medium" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Question & Answers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-h-screen flex flex-col">
    <nav class="bg-white shadow">
      <div class="mx-auto max-w-5xl px-2 sm:px-6 lg:px-8">
        <div class="relative flex h-16 justify-between">
          <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
            <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-500" aria-controls="mobile-menu" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
    
              <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
            <div class="hidden sm:ml-6 sm:flex sm:space-x-8">
              <%= link_to 'Latest Questions', questions_path, class: "inline-flex items-center border-b-2 border-blue-500 px-1 pt-1 text-sm font-medium text-gray-900" %>

            </div>
          </div>
        </div>
      </div>

      <div class="sm:hidden" id="mobile-menu">
        <div class="space-y-1 pt-2 pb-4">
          <%= link_to 'Latest Questions', questions_path, class: "block border-l-4 border-blue-500 bg-blue-50 py-2 pl-3 pr-4 text-base font-medium text-blue-700" %>

        </div>
      </div>
    </nav>

    <main class="container max-w-5xl mx-auto mt-14 px-2 sm:px-6 lg:px-8">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>

      <%= yield %>
    </main>

    <footer class="bg-white mt-auto pt-24">
      <div class="mx-auto max-w-7xl py-12 px-4 sm:px-6 md:flex md:items-center md:justify-between lg:px-8">
        <div class="flex justify-center space-x-6 md:order-2">
          <a href="https://github.com/joshjacksthrow/messageboard" class="text-gray-400 hover:text-gray-500">
            <span class="sr-only">GitHub</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
            </svg>
          </a>
        </div>
        <div class="mt-8 md:order-1 md:mt-0">
          <%= form_with url: "/questions/purge", method: :post do |form| %>
            <p class="">Q&A Technical. <%= form.submit "Clear Questions", class: "underline cursor-pointer" %>.</p>
            
          <% end %>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, class: "relative") do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg my-3">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="overflow-hidden rounded-lg border border-gray-300 shadow-sm focus-within:border-blue-500 focus-within:ring-1 focus-within:ring-blue-500">
    <label for="title" class="sr-only">Title</label>
    <%= form.text_field :title, class: "block w-full border-0 pt-2.5 text-lg font-medium placeholder-gray-500 focus:ring-0", placeholder: "Write a short title for your question..." %>

    <label for="description" class="sr-only">Description</label>
    <%= form.text_area :body, class: "block w-full resize-none border-0 py-0 placeholder-gray-500 focus:ring-0 sm:text-sm", placeholder: "Write the body of your question..." %>

    <!-- Spacer element to match the height of the toolbar -->
    <div aria-hidden="true">
      <div class="py-2">
        <div class="h-9"></div>
      </div>
      <div class="h-px"></div>
      <div class="py-2">
        <div class="py-px">
          <div class="h-9"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="absolute inset-x-px bottom-0">
    <div class="flex items-center justify-between space-x-3 border-t border-gray-200 px-2 py-2 sm:px-3">
      <div class="flex">
      
      </div>
      <div class="flex-shrink-0">
       <%= form.submit class: "inline-flex items-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2" %>
      </div>
    </div>
  </div>

<% end %>

app/views/questions/_question.html.erb
<%= link_to question, class: "block hover:bg-gray-200 rounded p-4" do %>
  <div id="<%= dom_id question %>" >
    <h3 class="text-2xl underline"><%= question.title %></h3>
    <p><%= question.body %></p>


    <h6 class="text-gray-400 text-sm">
      <span class="font-bold"><%= pluralize(question.answers.count, "answer") %></span>
      Asked on <%= question.created_at.to_s(:human) %>
    <h6>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div class="w-full space-y-4">
  <%= link_to "Back to question", @question, class: "rounded-lg py-2 px-4 bg-gray-100 inline-block font-medium" %>
  
  <h1 class="font-bold text-4xl">Editing question</h1>

  <%= render "form", question: @question %>
</div>

app/views/questions/index.html.erb
<div class="w-full" data-controller="questions">
  <div class="flex justify-between items-center sm:flex-row flex-col">
    <h1 class="font-bold text-4xl mb-4">Latest Questions</h1>
    <%= link_to 'Ask a question', new_question_path, class: "rounded-lg py-2 px-4 bg-blue-600 text-white block font-medium" %>
  </div>

  <hr class="my-4">

  <div class="bg-yellow-300 text-yellow-900 px-4 py-2 mb-2" data-questions-target="banner" hidden>
    <span>New questions have been posted, refresh to view</span>
  </div>


  <% if @questions.empty? %>
    <%= render partial: "shared/empty", locals: { name: "question", action: new_question_path } %>
  <% end %>

  <div id="questions" class="min-w-full">
    <%= render @questions %>
  </div>
</div>

app/views/questions/new.html.erb
<div class="w-full space-y-4">
  <h1 class="font-bold text-4xl">Ask a question</h1>

  <%= render "form", question: @question %>
</div>

app/views/questions/show.html.erb
<div class="mx-auto w-full">
  <div class="flex justify-between items-center">
    <div class="flex items-center space-x-4">
    </div>
  </div>

  <div class="md:flex md:items-center md:justify-between">
    <div class="min-w-0 flex-1">
      <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight"><%= @question.title %></h2>
    </div>
    <div class="mt-4 flex md:mt-0 md:ml-4">
    <%= link_to 'Edit', edit_question_path(@question), class: "inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2" %>
    <%= button_to 'Delete', question_path(@question), method: :delete, class: "ml-3 inline-flex items-center rounded-md border border-transparent bg-red-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2" %>
    </div>
  </div>


  <p class="mt-4"><%= @question.body %></p>
  
</div>

<hr class="my-8">

<div id="questions" class="min-w-full">
  <% if @question.answers.empty? %>
    <%= render partial: "shared/empty", locals: { name: "answer", action: new_question_answer_path(@question) } %>
 
  <% else %>
    <%= render @question.answers %>
    <%= link_to "Add an answer", new_question_answer_path(@question), class: "inline-flex items-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2" %>
  <% end %>

</div>

app/views/shared/_empty.erb
<div class="text-center">
  <svg class="mx-auto h-12 w-12 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9 5.25h.008v.008H12v-.008z" />
  </svg>

  <h3 class="mt-2 text-sm font-medium text-gray-900">No <%= name %>s</h3>
  <p class="mt-1 text-sm text-gray-500">Get started by creating a new <%= name %>.</p>
  <div class="mt-6">
    <%= link_to action, class: "inline-flex items-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2" do %>

      <!-- Heroicon name: mini/plus -->
      <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
      </svg>
      

      New <%= name %>
    <% end %>
  </div>
</div>